version: '3.8'
services:
  kak_bank:
    container_name: 'mobile-banking'
    #    image: 'surveybox_stage:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3003:8080'   #follow you port
    volumes:
      - '/home/lyhou/mobile-banking/images:/home/ite/media'
# what i want to explain to you is like see